### ISSUE TITLE
Apps freezing

### ISSUE THREAD

**Issue by Kruemelmann** [tobhe/ubuntu-asahi#167]
Applications freeze

Hello everyone, for a few days now I have had the problem that my applications keep freezing. Especially firefox seems to be affected (but the problem is not limited to the browser). At first I thought it was a browser problem but even after reinstalling it several times it still freezes.

After a little search in the system logs I found the following error:
`
2025-03-19T06:31:47.125974+01:00 localhost tracker-miner-fs-3[149448]: (tracker-extract-3:149448): GLib-
GIO-WARNING **: 06:31:47.125: Error creating IO channel for /proc/self/mountinfo: Invalid argument (g-io
-error-quark, 13) 
`

And after further searching on the internet I came across the issue `https://gitlab.gnome.org/GNOME/localsearch/-/issues/315` which describes the error pretty well. As of the last comment, the problem seems to exist in ubuntu as well, but I only experience it in combination with asahi on the mac (that's why I opened the issue here) but I can move it if you like

**Comment by tobhe** [comment]
I think in this case the best way to getting it fixed would be pointing a proper Ubuntu bug on launchpad and linking the upstream discussion. Looks like it was fixed at some point but 24.04 would need a backport.

**Comment by Kruemelmann** [comment]
Ok:) to follow up on this one:
I found an older issue in launchpad matching the error (it links back to the issue I added to the description)

I have continued to search for the problem because it makes the browser almost unusable.
Unfortunately, I didn't know exactly where to look for the error, so I checked the system logs.
I noticed an error that is related to wireplumber.

Here is the error:
``
2025-03-21T13:57:20.613459+01:00 localhost wireplumber[2317]: <WpSiAudioAdapter:0xaaaad6eb7c30> tried to link on last rescan, not retrying

2025-03-21T13:57:20.613518+01:00 localhost wireplumber[2317]: <WpSiAudioAdapter:0xaaaad6de0db0> tried to link on last rescan, not retrying

2025-03-21T13:57:20.613576+01:00 localhost wireplumber[2317]: <WpSiAudioAdapter:0xaaaad6e00f30> tried to link on last rescan, not retrying

2025-03-21T13:57:20.613854+01:00 localhost wireplumber[2317]: <WpSiStandardLink:0xaaaad6f17430> 6 of 6 PipeWire links failed to activate

2025-03-21T13:57:20.613944+01:00 localhost wireplumber[2317]: <WpSiAudioAdapter:0xaaaad6bd11d0> tried to link on last rescan, not retrying
``

This is only an impression, so especially the first few messages are spammed into the system log.

With that in mind, it's important to note that although I didn't have a microphone before (not really supported by asahi), I did have speaker sound from the built-in system. This no longer works either. In addition, I no longer see a microphone and speaker in the top right of the battery display menu, but only a headset (but I don't have a headset plugged in), so I no longer get any sound.

Could the errors be related because otherwise i don't know where to find the error


I know that the GitHub issues are not a place for individual problems. Honestly I didn't know where to go sorry for that since i cant find the error. I use asahi on a daily basis and hope to find the error somehow because the freezing makes the system almost unusable

**Comment by tobhe** [comment]
> With that in mind, it's important to note that although I didn't have a microphone before (not really supported by asahi), I did have speaker sound from the built-in system. This no longer works either. In addition, I no longer see a microphone and speaker in the top right of the battery display menu, but only a headset (but I don't have a headset plugged in), so I no longer get any sound.

Good to know. There seems to be a bug in the latest version of the asahi-audio package. I will keep an eye out for updates but I know that it has been discussed upstream so there will hopefully be a fix soon. On the plus side you will also get mic support :)

**Comment by Kruemelmann** [comment]
Thank you very much :) this is very good news because to be honest i was afraid i would have to completely reinstall my system and jump to an old version.

Thank you by the way for your constant effort in this project :) i really enjoy using it.

**Comment by tobhe** [comment]
There have been a bunch of package updates this week, I'd expect that those should fix the audio issues you were seeing. Can you confirm that it works after updating?

**Comment by Kruemelmann** [comment]
I have updated my system to the latest version. But unfortunately, I still have the problems with the freezing and the sound. I have now narrowed the problem down to the point where I am relatively certain that the apps freeze whenever the application tries to access audio output or input. I took some screenshots after the update, as I am no longer able to change the output via the gui.


![Image](https://github.com/user-attachments/assets/c18297c3-4174-49ff-a936-ba2c2d36338b)

![Image](https://github.com/user-attachments/assets/dc2d2e72-b09a-4fd3-8539-00237ae7a851)

The last one is a screenshot that captures the behavior from the system logs when an application tries to access an audio device:

![Image](https://github.com/user-attachments/assets/ad1dd779-57be-4312-be81-15995732c234)

**Comment by tobhe** [comment]
Weird. can you check which wireplumber and pipewire version you have installed?

**Comment by tobhe** [comment]
a recommendation that has come up in the fedora asahi dev chat a few times with unexplainable sound issues was deleting `~/.local/state/wireplumber` so maybe that helps in your case

**Comment by Kruemelmann** [comment]
![Image](https://github.com/user-attachments/assets/eb872d94-697a-4ac2-a369-73dbedde05e5)
![Image](https://github.com/user-attachments/assets/53167d5a-54b4-432d-84bb-188e5cee6f7f)

I deleted the folder, but the error still exists. Do you know if it is possible to reset the configs of wireplumber and pipewire to a default state?

**Comment by tobhe** [comment]
You could probably delete `~/.config/wireplumber` if it is user configuration or apt purge and reinstall the package. Can you also show `apt list --installed | grep pipewire` and `apt list --installed | grep asahi`?

**Comment by Kruemelmann** [comment]
apt list --installed | grep pipewire :

![Image](https://github.com/user-attachments/assets/5c8fd4cc-1d72-4f0d-a1c4-f1c601098a1d)

apt list --installed | grep asahi :

![Image](https://github.com/user-attachments/assets/d526576b-39b6-4a0e-8db6-c495875d13f5)
![Image](https://github.com/user-attachments/assets/9786f3e2-2c18-4f5d-9648-ce1372876d5c)

I have tried to delete and reboot, but problem still exists:/

**Comment by tobhe** [comment]
hm I think I see what the problem might be. Do you have a `/etc/apt/preferences.d/ubuntu-asahi.pref` file on your system? that SHOULD be part of the ubuntu-asahi package.
Your pipwire version is not the one I'd expect. It should be `pipewire - 1.0.5-1ubuntu2.0asahi0` if the pinning works correctly...
easy to fix with an update in the ppa but I wonder why the pinning didn't work in the first place.

**Comment by Kruemelmann** [comment]
I dont have a '/etc/apt/preferences.d/ubuntu-asahi.pref' but after some digging in the system i found out that i have a '/etc/apt/preferences.d.save/preferences.d/ubuntu-asahi.pref'
the content of this is:
`
Package: *

Pin: release o=LP-PPA-ubuntu-asahi-ubuntu-asahi

Pin-Priority: 1001
`

do you know why this happens? can i simply move the *.save folder so that the path matches the one you wrote to me?

**Comment by tobhe** [comment]
> do you know why this happens? can i simply move the *.save folder so that the path matches the one you wrote to me?

yes, that should work

It might be a problem related to release upgrades, I'll have to dig a little deeper to see why it might have moved that. We specifically configure the release updater not to touch the ppa config.

**Comment by Kruemelmann** [comment]
Ah just found out that it could be a path problem, maybe. 

I have a /etc/apt/preferences.d/preferences.d/ubuntu-asahi.pref

I will try to move it and see if it works after that.

**Comment by tobhe** [comment]
huh yes that is wrong

**Comment by Kruemelmann** [comment]
Ok yes that fixed the sound problem:) the output sound works fine. I think I'll wait for a few weeks to see if the upcoming changes in asahi-audio fix the mic.

I've already said it, but I'd like to say it again: Thank you for your patience with me.

I assume that the freezing should now also be solved. So I'll close the issue and if it still happens I'll just open it again :)
As I said, thank you very much:)

**Comment by tobhe** [comment]
Well thanks you for helping me with all the info! I'll try to find the root cause and see if we can fix this properly.

**Comment by tobhe** [comment]
Oh one more thing you could maybe check for me. What does `dpkg -L ubuntu-asahi` print? wonder if that also shows the `preferences.d/preferences/d`.

**Comment by Kruemelmann** [comment]
This looks fine i think:

![Image](https://github.com/user-attachments/assets/9b7b4518-a8a2-4d6e-a9c1-0482e545219d)

**Comment by tobhe** [comment]
Funny. so that shows the correct file path. Thanks, I think I have everything I need now!
